entries:
  - env: DEV
    product: FORECASTING
    username: maya
    function: ADMIN
  - env: QA
    product: FORECASTING
    username: alex
    function: ADMIN
  - env: PROD
    product: FORECASTING
    username: renee
    function: ADMIN

