entries:
  - env: DEV
    product: FORECASTING
    source: INVENTORY
    access_level: SHARED
  - env: QA
    product: FORECASTING
    source: INVENTORY
    access_level: SHARED
  - env: PROD
    product: FORECASTING
    source: INVENTORY
    access_level: SHARED

