name: CLI Setup
description: A composite action to install the toolkit and connect to snowflake
inputs:
  toolkit_cli_download_token:
    description: "Token to download the toolkit"
    required: true
    default: ""
  toolkit_cli_version:
    description: "Version of the toolkit cli to install"
    required: true
    default: "0.50.0"
  snowflake_private_key_pem:
    description: "Snowflake private key in pem format"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Cache Toolkit CLI
      id: cache-toolkit-cli
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: cli-install
        key: toolkit-cli-${{ inputs.toolkit_cli_version }}
    - name: Download the toolkit-cli
      if: ${{ steps.cache-toolkit-cli.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        TOOLKIT_CLI_DOWNLOAD_URL="https://repo.phdata.io/toolkit-cli/${{ inputs.toolkit_cli_version }}/toolkit-cli-${{ inputs.toolkit_cli_version }}.zip"
        curl --fail --output toolkit-cli.zip "$TOOLKIT_CLI_DOWNLOAD_URL"
        unzip toolkit-cli.zip

        zip_name="${TOOLKIT_CLI_DOWNLOAD_URL##*/}"
        versioned_dir="${zip_name%.zip}"
        if [ -d "$versioned_dir" ]; then
          # this is an older zip file that includes the version in the directory name, so rename it
          echo "Moving $versioned_dir -> toolkit-cli"
          mv "$versioned_dir" toolkit-cli
        fi

    - name: Add toolkit to PATH
      shell: bash
      run: readlink -f cli-install >> $GITHUB_PATH

    - name: Write Snowflake private key
      shell: bash
      run: |
        (umask  077 ; echo ${{ inputs.snowflake_private_key_pem }} | base64 --decode > /tmp/snowflake_key.p8)
        echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: corretto
