-- Create hybrid tables

CREATE SCHEMA hybrid;

CREATE OR REPLACE HYBRID TABLE hybrid.customer (
	ID INTEGER NOT NULL,
	FIRST_NAME TEXT,
	LAST_NAME TEXT NOT NULL,
	STATE TEXT,
	ZIP_CODE TEXT,
    constraint PK_0 primary key (ID)
);

CREATE OR REPLACE HYBRID TABLE hybrid.product (
	ID INTEGER NOT NULL,
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	CATEGORY TEXT NOT NULL,
	LAUNCH_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	DISCONTINUED_TIMESTAMP TIMESTAMP_NTZ(9),
	COST NUMBER(6,2) NOT NULL,
	PRICE NUMBER(7,2),
    constraint PK_0 primary key (ID)
);

CREATE OR REPLACE HYBRID TABLE hybrid.order_history (
	ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	SALE_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	RETURN_TIMESTAMP TIMESTAMP_NTZ(9),
    constraint PK_0 primary key (ID)
);

--  Datagen can't insert in foreign-key constrained tables yet
-- 	constraint FK_0 foreign key (PRODUCT_ID) references HYBRID.PRODUCT(ID),
-- 	constraint FK_1 foreign key (CUSTOMER_ID) references HYBRID.CUSTOMER(ID)

--  Create columnar tables

CREATE SCHEMA columnar;

CREATE OR REPLACE TABLE columnar.customer (
	ID INTEGER NOT NULL,
	FIRST_NAME TEXT,
	LAST_NAME TEXT NOT NULL,
	STATE TEXT,
	ZIP_CODE TEXT,
	constraint PK_0 primary key (ID)
);

CREATE OR REPLACE TABLE columnar.product (
	ID INTEGER NOT NULL,
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	CATEGORY TEXT NOT NULL,
	LAUNCH_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	DISCONTINUED_TIMESTAMP TIMESTAMP_NTZ(9),
	COST NUMBER(6,2) NOT NULL,
	PRICE NUMBER(7,2),
	constraint PK_0 primary key (ID)
);

CREATE OR REPLACE TABLE columnar.order_history (
	ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	SALE_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	RETURN_TIMESTAMP TIMESTAMP_NTZ(9),
    constraint PK_0 primary key (ID),
	constraint FK_0 foreign key (PRODUCT_ID) references columnar.PRODUCT(ID),
	constraint FK_1 foreign key (CUSTOMER_ID) references columnar.CUSTOMER(ID)
);
