USE DATABASE DEMO_SILVER_${DEMO_NONCE};
USE SCHEMA MAIN;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY        NUMBER(38, 0) NOT NULL,
    CUSTOMER_ID         NUMBER(38, 0) NOT NULL,
    FIRST_NAME          VARCHAR(50)   NOT NULL,
    LAST_NAME           VARCHAR(50)   NOT NULL,
    EMAIL               VARCHAR(100),
    GENDER              VARCHAR(10),
    BIRTH_YEAR          NUMBER(4, 0),
    CITY                VARCHAR(50),
    STATE               VARCHAR(50),
    SIGNUP_DATE         DATE          NOT NULL
);

CREATE OR REPLACE TABLE DIM_PRODUCT_CATEGORY (
    CATEGORY_KEY        NUMBER(38, 0) NOT NULL,
    CATEGORY_ID         NUMBER(38, 0) NOT NULL,
    CATEGORY_NAME       VARCHAR(50)   NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(200)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY         NUMBER(38, 0) NOT NULL,
    SKU                 NUMBER(38, 0) NOT NULL,
    PRODUCT_NAME        VARCHAR(100)  NOT NULL,
    CATEGORY_KEY        NUMBER(38, 0) NOT NULL,
    LIST_PRICE          NUMBER(10, 2) NOT NULL,
    IS_ACTIVE           BOOLEAN       NOT NULL
);

CREATE OR REPLACE TABLE DIM_STORE_LOCATION (
    LOCATION_KEY        NUMBER(38, 0) NOT NULL,
    LOCATION_ID         NUMBER(38, 0) NOT NULL,
    CITY                VARCHAR(50)   NOT NULL,
    STATE               VARCHAR(50)   NOT NULL,
    COUNTRY             VARCHAR(50)   NOT NULL,
    POSTAL_CODE         VARCHAR(10)
);

CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY           NUMBER(38, 0) NOT NULL,
    STORE_CODE          NUMBER(38, 0) NOT NULL,
    STORE_NAME          VARCHAR(100)  NOT NULL,
    LOCATION_KEY        NUMBER(38, 0) NOT NULL,
    OPEN_DATE           DATE          NOT NULL
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY            NUMBER(38, 0) NOT NULL,
    DATE_VALUE          DATE          NOT NULL,
    YEAR                NUMBER(4, 0)  NOT NULL,
    QUARTER             NUMBER(1, 0)  NOT NULL,
    MONTH               NUMBER(2, 0)  NOT NULL,
    DAY_OF_MONTH        NUMBER(2, 0)  NOT NULL,
    DAY_OF_WEEK         NUMBER(1, 0)  NOT NULL,
    DAY_NAME            VARCHAR(10)   NOT NULL,
    IS_WEEKEND          BOOLEAN       NOT NULL
);

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY           NUMBER(38, 0) NOT NULL,
    ORDER_ID            NUMBER(38, 0) NOT NULL,
    ORDER_LINE_ID       NUMBER(38, 0) NOT NULL,
    DATE_KEY            NUMBER(38, 0) NOT NULL,
    CUSTOMER_KEY        NUMBER(38, 0) NOT NULL,
    PRODUCT_KEY         NUMBER(38, 0) NOT NULL,
    STORE_KEY           NUMBER(38, 0) NOT NULL,
    QUANTITY            NUMBER(3, 0)  NOT NULL,
    UNIT_PRICE          NUMBER(10, 2) NOT NULL,
    DISCOUNT_PCT        NUMBER(5, 2),
    GROSS_AMOUNT        NUMBER(12, 2) NOT NULL,
    NET_AMOUNT          NUMBER(12, 2) NOT NULL,
    ORDER_STATUS        VARCHAR(20)   NOT NULL,
    CHANNEL             VARCHAR(10)   NOT NULL
);
