USE DATABASE DEMO_SILVER_${DEMO_NONCE};
USE SCHEMA MAIN;

TRUNCATE TABLE DIM_CUSTOMER;
INSERT INTO DIM_CUSTOMER (
    CUSTOMER_KEY, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL,
    GENDER, BIRTH_YEAR, CITY, STATE, SIGNUP_DATE
)
SELECT
    -- Natural numeric key used directly as the surrogate. Avoids HASH() which
    -- returns 64-bit values that overflow downstream STDDEV during profiling
    -- (SUM(x^2) over 10^18-scale values blows past NUMBER(38,0)).
    CUSTOMER_ID                                             AS CUSTOMER_KEY,
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    LOWER(EMAIL)                                            AS EMAIL,
    UPPER(GENDER)                                           AS GENDER,
    BIRTH_YEAR,
    INITCAP(CITY)                                           AS CITY,
    UPPER(STATE)                                            AS STATE,
    CAST(SIGNUP_AT AS DATE)                                 AS SIGNUP_DATE
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.CUSTOMERS_RAW;

TRUNCATE TABLE DIM_PRODUCT_CATEGORY;
INSERT INTO DIM_PRODUCT_CATEGORY (
    CATEGORY_KEY, CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESCRIPTION
)
SELECT
    CATEGORY_ID         AS CATEGORY_KEY,
    CATEGORY_ID,
    CATEGORY_NAME,
    CATEGORY_DESCRIPTION
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.PRODUCT_CATEGORIES_RAW;

TRUNCATE TABLE DIM_PRODUCT;
INSERT INTO DIM_PRODUCT (
    PRODUCT_KEY, SKU, PRODUCT_NAME, CATEGORY_KEY, LIST_PRICE, IS_ACTIVE
)
SELECT
    p.SKU                                                   AS PRODUCT_KEY,
    p.SKU,
    p.PRODUCT_NAME,
    p.CATEGORY_ID                                           AS CATEGORY_KEY,
    p.LIST_PRICE,
    CASE WHEN p.ACTIVE_FLAG = 'Y' THEN TRUE ELSE FALSE END  AS IS_ACTIVE
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.PRODUCTS_RAW p;

TRUNCATE TABLE DIM_STORE_LOCATION;
INSERT INTO DIM_STORE_LOCATION (
    LOCATION_KEY, LOCATION_ID, CITY, STATE, COUNTRY, POSTAL_CODE
)
SELECT
    LOCATION_ID         AS LOCATION_KEY,
    LOCATION_ID,
    INITCAP(CITY)       AS CITY,
    UPPER(STATE)        AS STATE,
    UPPER(COUNTRY)      AS COUNTRY,
    POSTAL_CODE
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.STORE_LOCATIONS_RAW;

TRUNCATE TABLE DIM_STORE;
INSERT INTO DIM_STORE (
    STORE_KEY, STORE_CODE, STORE_NAME, LOCATION_KEY, OPEN_DATE
)
SELECT
    s.STORE_CODE            AS STORE_KEY,
    s.STORE_CODE,
    s.STORE_NAME,
    s.LOCATION_ID           AS LOCATION_KEY,
    s.OPEN_DATE
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.STORES_RAW s;

TRUNCATE TABLE DIM_DATE;
INSERT INTO DIM_DATE (
    DATE_KEY, DATE_VALUE, YEAR, QUARTER, MONTH,
    DAY_OF_MONTH, DAY_OF_WEEK, DAY_NAME, IS_WEEKEND
)
WITH ALL_DATES AS (
    SELECT DISTINCT CAST(ORDER_TS AS DATE) AS DATE_VALUE
    FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.ORDERS_RAW
    UNION
    SELECT DISTINCT CAST(SIGNUP_AT AS DATE)
    FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.CUSTOMERS_RAW
    UNION
    SELECT DISTINCT OPEN_DATE
    FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.STORES_RAW
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD'))              AS DATE_KEY,
    DATE_VALUE,
    YEAR(DATE_VALUE)                                        AS YEAR,
    QUARTER(DATE_VALUE)                                     AS QUARTER,
    MONTH(DATE_VALUE)                                       AS MONTH,
    DAY(DATE_VALUE)                                         AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_VALUE)                                   AS DAY_OF_WEEK,
    DAYNAME(DATE_VALUE)                                     AS DAY_NAME,
    DAYOFWEEK(DATE_VALUE) IN (0, 6)                         AS IS_WEEKEND
FROM ALL_DATES
WHERE DATE_VALUE IS NOT NULL;

TRUNCATE TABLE FACT_SALES;
INSERT INTO FACT_SALES (
    SALES_KEY, ORDER_ID, ORDER_LINE_ID, DATE_KEY,
    CUSTOMER_KEY, PRODUCT_KEY, STORE_KEY,
    QUANTITY, UNIT_PRICE, DISCOUNT_PCT,
    GROSS_AMOUNT, NET_AMOUNT, ORDER_STATUS, CHANNEL
)
SELECT
    ol.ORDER_LINE_ID                                        AS SALES_KEY,
    o.ORDER_ID,
    ol.ORDER_LINE_ID,
    TO_NUMBER(TO_CHAR(CAST(o.ORDER_TS AS DATE), 'YYYYMMDD')) AS DATE_KEY,
    o.CUSTOMER_ID                                           AS CUSTOMER_KEY,
    ol.SKU                                                  AS PRODUCT_KEY,
    o.STORE_CODE                                            AS STORE_KEY,
    ol.QUANTITY,
    ol.UNIT_PRICE,
    ol.DISCOUNT_PCT,
    ol.QUANTITY * ol.UNIT_PRICE                             AS GROSS_AMOUNT,
    ol.QUANTITY * ol.UNIT_PRICE
        * (1 - COALESCE(ol.DISCOUNT_PCT, 0) / 100.0)        AS NET_AMOUNT,
    o.ORDER_STATUS,
    o.CHANNEL
FROM DEMO_BRONZE_${DEMO_NONCE}.MAIN.ORDER_LINES_RAW ol
JOIN DEMO_BRONZE_${DEMO_NONCE}.MAIN.ORDERS_RAW o
    ON ol.ORDER_ID = o.ORDER_ID;
