USE DATABASE DEMO_GOLD_${DEMO_NONCE};
USE SCHEMA MAIN;

TRUNCATE TABLE GOLD_SALES_FULL;
INSERT INTO GOLD_SALES_FULL (
    ORDER_ID, ORDER_LINE_ID, ORDER_DATE, ORDER_YEAR, ORDER_QUARTER, ORDER_MONTH,
    ORDER_DAY_NAME, ORDER_IS_WEEKEND, ORDER_STATUS, CHANNEL,
    CUSTOMER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME, CUSTOMER_EMAIL,
    CUSTOMER_GENDER, CUSTOMER_BIRTH_YEAR, CUSTOMER_CITY, CUSTOMER_STATE,
    CUSTOMER_SIGNUP_DATE,
    SKU, PRODUCT_NAME, PRODUCT_LIST_PRICE, PRODUCT_IS_ACTIVE,
    CATEGORY_ID, CATEGORY_NAME,
    STORE_CODE, STORE_NAME, STORE_OPEN_DATE,
    STORE_CITY, STORE_STATE, STORE_COUNTRY, STORE_POSTAL_CODE,
    QUANTITY, UNIT_PRICE, DISCOUNT_PCT, GROSS_AMOUNT, NET_AMOUNT
)
SELECT
    f.ORDER_ID,
    f.ORDER_LINE_ID,
    d.DATE_VALUE              AS ORDER_DATE,
    d.YEAR                    AS ORDER_YEAR,
    d.QUARTER                 AS ORDER_QUARTER,
    d.MONTH                   AS ORDER_MONTH,
    d.DAY_NAME                AS ORDER_DAY_NAME,
    d.IS_WEEKEND              AS ORDER_IS_WEEKEND,
    f.ORDER_STATUS,
    f.CHANNEL,

    c.CUSTOMER_ID,
    c.FIRST_NAME              AS CUSTOMER_FIRST_NAME,
    c.LAST_NAME               AS CUSTOMER_LAST_NAME,
    c.EMAIL                   AS CUSTOMER_EMAIL,
    c.GENDER                  AS CUSTOMER_GENDER,
    c.BIRTH_YEAR              AS CUSTOMER_BIRTH_YEAR,
    c.CITY                    AS CUSTOMER_CITY,
    c.STATE                   AS CUSTOMER_STATE,
    c.SIGNUP_DATE             AS CUSTOMER_SIGNUP_DATE,

    p.SKU,
    p.PRODUCT_NAME,
    p.LIST_PRICE              AS PRODUCT_LIST_PRICE,
    p.IS_ACTIVE               AS PRODUCT_IS_ACTIVE,
    pc.CATEGORY_ID,
    pc.CATEGORY_NAME,

    s.STORE_CODE,
    s.STORE_NAME,
    s.OPEN_DATE               AS STORE_OPEN_DATE,
    sl.CITY                   AS STORE_CITY,
    sl.STATE                  AS STORE_STATE,
    sl.COUNTRY                AS STORE_COUNTRY,
    sl.POSTAL_CODE            AS STORE_POSTAL_CODE,

    f.QUANTITY,
    f.UNIT_PRICE,
    f.DISCOUNT_PCT,
    f.GROSS_AMOUNT,
    f.NET_AMOUNT
FROM DEMO_SILVER_${DEMO_NONCE}.MAIN.FACT_SALES f
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_DATE d
    ON f.DATE_KEY = d.DATE_KEY
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_CUSTOMER c
    ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_PRODUCT p
    ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_PRODUCT_CATEGORY pc
    ON p.CATEGORY_KEY = pc.CATEGORY_KEY
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_STORE s
    ON f.STORE_KEY = s.STORE_KEY
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_STORE_LOCATION sl
    ON s.LOCATION_KEY = sl.LOCATION_KEY;
