-- Simulated analyst / BI workload against the bad-gold layer.
-- Run this file in a loop via `run.sh simulate-workload` so ACCOUNT_USAGE.QUERY_HISTORY
-- accumulates repeated query shapes for `ds history` / `ds lineage` to mine.

USE DATABASE DEMO_GOLD_${DEMO_NONCE};
USE SCHEMA MAIN;

-- 1. Total revenue by year/quarter
SELECT ORDER_YEAR, ORDER_QUARTER, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY ORDER_YEAR, ORDER_QUARTER
ORDER BY ORDER_YEAR, ORDER_QUARTER;

-- 2. Top 20 customers by lifetime net spend
SELECT CUSTOMER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME,
       SUM(NET_AMOUNT) AS LIFETIME_NET
FROM GOLD_SALES_FULL
WHERE ORDER_STATUS IN ('DELIVERED', 'SHIPPED')
GROUP BY CUSTOMER_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME
ORDER BY LIFETIME_NET DESC
LIMIT 20;

-- 3. Revenue by channel
SELECT CHANNEL, COUNT(DISTINCT ORDER_ID) AS ORDERS, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY CHANNEL;

-- 4. Revenue by product category
SELECT CATEGORY_NAME, SUM(NET_AMOUNT) AS REVENUE, SUM(QUANTITY) AS UNITS
FROM GOLD_SALES_FULL
GROUP BY CATEGORY_NAME
ORDER BY REVENUE DESC;

-- 5. Top 10 SKUs by gross
SELECT SKU, PRODUCT_NAME, SUM(GROSS_AMOUNT) AS GROSS
FROM GOLD_SALES_FULL
GROUP BY SKU, PRODUCT_NAME
ORDER BY GROSS DESC
LIMIT 10;

-- 6. Weekend vs weekday revenue
SELECT ORDER_IS_WEEKEND, COUNT(DISTINCT ORDER_ID) AS ORDERS, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY ORDER_IS_WEEKEND;

-- 7. Sales by state
SELECT STORE_STATE, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY STORE_STATE
ORDER BY REVENUE DESC;

-- 8. Sales by store
SELECT STORE_CODE, STORE_NAME, SUM(NET_AMOUNT) AS REVENUE,
       COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM GOLD_SALES_FULL
GROUP BY STORE_CODE, STORE_NAME
ORDER BY REVENUE DESC;

-- 9. Returned-order rate by channel
SELECT CHANNEL,
       COUNT_IF(ORDER_STATUS = 'RETURNED') / NULLIF(COUNT(*), 0) AS RETURN_RATE
FROM GOLD_SALES_FULL
GROUP BY CHANNEL;

-- 10. Average order value
SELECT ORDER_ID, SUM(NET_AMOUNT) AS ORDER_NET
FROM GOLD_SALES_FULL
GROUP BY ORDER_ID
ORDER BY ORDER_NET DESC
LIMIT 50;

-- 11. Monthly trend
SELECT ORDER_YEAR, ORDER_MONTH, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY ORDER_YEAR, ORDER_MONTH
ORDER BY ORDER_YEAR, ORDER_MONTH;

-- 12. Customer cohort: customers who signed up vs total revenue they drove
SELECT YEAR(CUSTOMER_SIGNUP_DATE) AS COHORT_YEAR,
       COUNT(DISTINCT CUSTOMER_ID) AS COHORT_SIZE,
       SUM(NET_AMOUNT) AS COHORT_REVENUE
FROM GOLD_SALES_FULL
GROUP BY YEAR(CUSTOMER_SIGNUP_DATE)
ORDER BY COHORT_YEAR;

-- 13. Discount usage
SELECT CASE
           WHEN DISCOUNT_PCT IS NULL THEN 'NO_DISCOUNT'
           WHEN DISCOUNT_PCT < 10 THEN 'UNDER_10'
           WHEN DISCOUNT_PCT < 20 THEN 'UNDER_20'
           ELSE '20_PLUS'
       END AS BAND,
       COUNT(*) AS LINES,
       SUM(GROSS_AMOUNT - NET_AMOUNT) AS DISCOUNT_DOLLARS
FROM GOLD_SALES_FULL
GROUP BY BAND;

-- 14. Gender x category mix (note: gender is nullable in raw, so demo-real)
SELECT CUSTOMER_GENDER, CATEGORY_NAME, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
WHERE CUSTOMER_GENDER IS NOT NULL
GROUP BY CUSTOMER_GENDER, CATEGORY_NAME
ORDER BY CUSTOMER_GENDER, REVENUE DESC;

-- 15. Active vs inactive product revenue split
SELECT PRODUCT_IS_ACTIVE, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY PRODUCT_IS_ACTIVE;

-- 16. Repeat-customer detection
SELECT CUSTOMER_ID, COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
FROM GOLD_SALES_FULL
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID) > 1
ORDER BY ORDER_COUNT DESC
LIMIT 100;

-- 17. Day-of-week revenue
SELECT ORDER_DAY_NAME, SUM(NET_AMOUNT) AS REVENUE,
       COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM GOLD_SALES_FULL
GROUP BY ORDER_DAY_NAME;

-- 18. Customer age band (derived from birth year)
SELECT CASE
           WHEN CUSTOMER_BIRTH_YEAR IS NULL THEN 'UNKNOWN'
           WHEN CUSTOMER_BIRTH_YEAR > 2000 THEN 'GEN_Z'
           WHEN CUSTOMER_BIRTH_YEAR > 1980 THEN 'MILLENNIAL'
           WHEN CUSTOMER_BIRTH_YEAR > 1965 THEN 'GEN_X'
           ELSE 'BOOMER_OR_OLDER'
       END AS AGE_BAND,
       SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY AGE_BAND;

-- 19. Joining bad-gold back to silver to compare snapshot freshness
-- (analyst routinely needs current product price, which the snapshot can't give them history for)
SELECT gs.SKU, gs.PRODUCT_NAME,
       gs.LIST_PRICE AS SNAPSHOT_LIST_PRICE,
       sp.LIST_PRICE AS SILVER_LIST_PRICE,
       gs.SNAPSHOT_LOADED_AT
FROM GOLD_PRODUCT_SNAPSHOT gs
JOIN DEMO_SILVER_${DEMO_NONCE}.MAIN.DIM_PRODUCT sp
    ON gs.SKU = sp.SKU
LIMIT 100;

-- 20. Customer state coverage check
SELECT CUSTOMER_STATE, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMERS
FROM GOLD_SALES_FULL
WHERE CUSTOMER_STATE IS NOT NULL
GROUP BY CUSTOMER_STATE
ORDER BY CUSTOMERS DESC;

-- 21. Net amount distribution (analytics buckets)
SELECT WIDTH_BUCKET(NET_AMOUNT, 0, 5000, 10) AS BUCKET, COUNT(*) AS LINES
FROM GOLD_SALES_FULL
GROUP BY BUCKET
ORDER BY BUCKET;

-- 22. Last 30 days of revenue
SELECT ORDER_DATE, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
WHERE ORDER_DATE >= DATEADD(day, -30, CURRENT_DATE())
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

-- 23. Channel x category revenue
SELECT CHANNEL, CATEGORY_NAME, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY CHANNEL, CATEGORY_NAME;

-- 24. Top stores per state
SELECT STORE_STATE, STORE_NAME, SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY STORE_STATE, STORE_NAME
QUALIFY ROW_NUMBER() OVER (PARTITION BY STORE_STATE ORDER BY SUM(NET_AMOUNT) DESC) <= 3;

-- 25. Categories that drove returns
SELECT CATEGORY_NAME,
       COUNT_IF(ORDER_STATUS = 'RETURNED') AS RETURNS,
       COUNT(*)                            AS LINES
FROM GOLD_SALES_FULL
GROUP BY CATEGORY_NAME
ORDER BY RETURNS DESC;

-- 26. Snapshot freshness audit
SELECT MIN(SNAPSHOT_LOADED_AT) AS OLDEST_SNAPSHOT,
       MAX(SNAPSHOT_LOADED_AT) AS NEWEST_SNAPSHOT
FROM GOLD_CUSTOMER_SNAPSHOT;

-- 27. Order header rollup (demonstrates the OBT grain problem — these aggregates
-- double-count anything header-level because rows are at order-line grain)
SELECT ORDER_ID, ORDER_STATUS, MAX(ORDER_DATE) AS ORDER_DATE,
       SUM(NET_AMOUNT) AS ORDER_NET
FROM GOLD_SALES_FULL
GROUP BY ORDER_ID, ORDER_STATUS;

-- 28. Customer-level revenue with attributes pulled from header columns
-- (also demonstrates the OBT problem: customer attributes are denormalized
-- into every line, so any change to the customer is invisible historically)
SELECT CUSTOMER_ID, CUSTOMER_STATE, CUSTOMER_EMAIL,
       SUM(NET_AMOUNT) AS REVENUE
FROM GOLD_SALES_FULL
GROUP BY CUSTOMER_ID, CUSTOMER_STATE, CUSTOMER_EMAIL;

-- 29. Average lines per order
SELECT AVG(LINES_PER_ORDER) AS AVG_LINES
FROM (
    SELECT ORDER_ID, COUNT(*) AS LINES_PER_ORDER
    FROM GOLD_SALES_FULL
    GROUP BY ORDER_ID
);

-- 30. Active customers in last 90d
SELECT COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS_90D
FROM GOLD_SALES_FULL
WHERE ORDER_DATE >= DATEADD(day, -90, CURRENT_DATE());
