name: Access Tool

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

defaults:
  run:
    working-directory: access

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run common setup
        uses: ./.github/actions/common-setup
        with:
          toolkit_cli_download_token: ${{ secrets.toolkit_cli_download_token }}
          toolkit_cli_version: ${{ vars.toolkit_cli_version }}
          snowflake_private_key_pem: ${{ secrets.snowflake_private_key_pem }}

      - name: Scan snowflake
        run: toolkit access scan snowflake

      - name: Create HTML report
        run: toolkit access show snowflake:access:latest -o access-scan.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: access-scan
          path: access/access-scan.html
          if-no-files-found: error
