name: Snowflake Access Scan

permissions:
  contents: write
  contents: read

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

defaults:
  run:
    working-directory: tools/access

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  TOOLKIT_CLI_DOWNLOAD_TOKEN: ${{ secrets.toolkit_cli_download_token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./.github/actions/common-setup
        shell: bash
        with:
          toolkit_cli_download_token: $TOOLKIT_CLI_DOWNLOAD_TOKEN
          toolkit_cli_version: $TOOLKIT_CLI_VERSION
          snowflake_private_key_pem: $SNOWFLAKE_PRIVATE_KEY_PEM

      - name: Scan snowflake
        run: toolkit access scan snowflake

      - name: Create HTML report
        run: toolkit access show snowflake:access:latest -o access-scan.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: access-scan
          path: tools/access/access-scan.html
          if-no-files-found: error
