name: Snowflake Advisor Scan

permissions:
  contents: read
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./.github/actions/common-setup

      - name: Scan snowflake
        run: | 
          cd tools/advisor
          toolkit advisor scan snowflake

      - name: Create HTML report
        run: | 
          cd tools/advisor
          toolkit advisor show snowflake:check:latest -o advisor-scan.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: advisor-scan
          path: tools/advisor/advisor-scan.html
          if-no-files-found: error