name: Snowflake Advisor Scan

permissions:
  contents: read
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

defaults:
  run:
    working-directory: tools/advisor

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the toolkit-cli
        run: |
          set -euo pipefail

          curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
          unzip -jd install toolkit-cli.zip

      - name: Add toolkit to PATH
        run: readlink -f install >> $GITHUB_PATH

      - name: Write Snowflake private key
        run: |
          (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
          echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Scan snowflake
        run: toolkit advisor scan snowflake

      - name: Create HTML report
        run: toolkit advisor show snowflake:check:latest -o advisor-scan.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: advisor-scan
          path: tools/advisor/advisor-scan.html
          if-no-files-found: error
          overwrite: true