name: Snowflake Data Generation

permissions:
  contents: read
  contents: write

on:
  schedule:
    - cron: "0 23 * * *" # Runs every day at 11:00 p.m.

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./.github/actions/common-setup
         
      - name: Add data to snowflake 
        run: |
          cd tools/datagen
          toolkit datagen jdbc --append snowflake --spec specs/advanced-snowflake-spec.yaml
      
      - name: Scan snowflake  
        run: |
          cd tools/datagen
          toolkit datagen scan snowflake --filter SYNTHETIC_SALES --spec specs/synthetic-sales.yaml
      
      - name: Generate report
        run: |
          cd tools/datagen
          toolkit datagen show --output=datagen-sales-report.html specs/advanced-snowflake-spec.yaml

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: datagen-sales-report
          path: tools/datagen/datagen-sales-report.html
          if-no-files-found: error
            