name: Snowflake Data Source Reports

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

defaults:
  run:
    working-directory: tools/datasource

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run common setup
        uses: ./.github/actions/common-setup
        with:
          toolkit_cli_download_token: $TOOLKIT_CLI_DOWNLOAD_TOKEN
          toolkit_cli_version: $TOOLKIT_CLI_VERSION
          snowflake_private_key_pem: $SNOWFLAKE_PRIVATE_KEY_PEM

      - name: Scan snowflake
        run: |
          toolkit ds scan snowflake
          toolkit ds show snowflake:scan:latest --format html -o daily-ds-reports/ds-scan.html

      - name: Profile snowflake
        run: |
          toolkit ds profile snowflake:scan:latest
          toolkit ds show snowflake:profile:latest --format html -o daily-ds-reports/ds-profile.html

      - name: Diff snowflake
        run: |
          toolkit ds diff snowflake:profile:latest-1 snowflake:profile:latest 
          toolkit ds show snowflake.snowflake:diff:latest --format html -o daily-ds-reports/ds-diff.html
        continue-on-error: true

      - name: Commit snapshots to git
        run: |
          git add ./tools
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          commit_message="Add snapshot files - ${current-date}"
          git commit -m "${commit-message}"
          git push origin master

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: daily-ds-reports
          path: tools/datasource/daily-ds-reports/
          if-no-files-found: error

      - name: Remove old snapshots
        run: toolkit admin clean --approve --days=30
