name: Snowflake DS Reports

permissions:
  contents: read
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

defaults:
  run:
    working-directory: tools/datasource

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the toolkit-cli
        shell: bash
        run: |
          set -euo pipefail

          curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
          unzip -jd install toolkit-cli.zip

      - name: Run admin shell
        shell: bash
        run: readlink -f install >> $GITHUB_PATH

      - name: Write Snowflake private key
        shell: bash
        run: |
          (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
          echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto

      - name: Make daily scans directory
        shell: bash
        run: |
          if [ ! -d daily_ds_reports ]; then
            mkdir -p daily_ds_reports
          fi

      - name: Scan snowflake
        shell: bash
        run: |
          toolkit ds scan snowflake
          ds show snowflake:scan:latest --format html -o
          mv $(find . -maxdepth 1 -type f -name 'snowflake_scan_*') daily_ds_reports

      # - name: Move report into daily scans directory and dump report into renamed file
      #   shell: bash
      #   run: | 
      #     mv $(find . -maxdepth 1 -type f -name 'snowflake_check_*') daily_ds_reports
      #     cd daily_ds_reports/
      #     cp $(ls -t | head -n 1) daily_advisor_scan.html

      # - name: Upload reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: tools/datasource/daily_ds_reports/daily_advisor_scan.html
      #     if-no-files-found: error
      #     overwrite: true