name: Snowflake Data Generation

permissions:
  contents: read
  contents: write

on:
  schedule:
    - cron: "0 23 * * 0" # Runs every day Sunday at 11:00 p.m.

defaults:
  run:
    working-directory: tools/datagen

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the toolkit-cli
        shell: bash
        run: |
          set -euo pipefail

          curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
          unzip -jd install toolkit-cli.zip

      - name: Run admin shell
        shell: bash
        run: readlink -f install >> $GITHUB_PATH

      - name: Write Snowflake private key
        shell: bash
        run: |
          (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
          echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
        
        
      - name: Add generated data to snowflake
        shell: bash 
        run: toolkit datagen jdbc --append snowflake --spec tools/datagen/snowflake/advanced-snowflake-spec.yaml
      
      - name: Scan snowflake 
        shell: bash 
        run: toolkit datagen scan snowflake --filter SYNTHETIC_SALES --spec tools/datagen/snowflake/synthetic_sales.yaml
      
      - name: Generate report
        shell: bash
        run: toolkit datagen show --output=weekly_datagen_report.html tools/datagen/snowflake/synthetic_sales.yaml

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: weekly_datagen_report
          path: tools/datagen/weekly_datagen_report.html
          if-no-files-found: error
          overwrite: true
            