name: Provision Tool

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

defaults:
  run:
    working-directory: tools/provision

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run common setup
        uses: ./.github/actions/common-setup
        with:
          toolkit_cli_download_token: ${{ secrets.toolkit_cli_download_token }}
          toolkit_cli_version: ${{ vars.toolkit_cli_version }}
          snowflake_private_key_pem: ${{ secrets.snowflake_private_key_pem }}

      - name: Create metadata
        run: toolkit provision init --metadata

      - name: Plan on pull request
        if: github.event_name == 'pull_request'
        run: toolkit provision apply --plan

      - name: Apply changes on merge to master
        run: toolkit provision apply
        if: github.event_name != 'pull_request'
