name: Snowflake Provisioning

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_DOWNLOAD_URL: ${{ secrets.toolkit_cli_download_url }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  SNOWFLAKE_PRIVATE_KEY_FILE: ${{ vars.snowflake_private_key_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./.github/actions/common-setup

      - name: Create metadata
        run: |
          cd tools/provision
          toolkit provision init --metadata

      - name: Plan on pull request
        if: github.event_name == 'pull_request'
        run: |
          cd tools/provision
          toolkit provision apply --plan

      - name: Apply changes on merge to master
        run: |
          cd tools/provision
          toolkit provision apply
        if: github.event_name == 'push'
