name: Snowflake Provisioning

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

defaults:
  run:
    working-directory: tools/provision

env:
  TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
  TOOLKIT_CLI_VERSION: ${{ vars.toolkit_cli_version }}
  SNOWFLAKE_PRIVATE_KEY_PEM: ${{ secrets.snowflake_private_key_pem }}
  SNOWFLAKE_USER: ${{ vars.snowflake_user }}
  SNOWFLAKE_URL: ${{ secrets.snowflake_url }}
  TOOLKIT_CLI_DOWNLOAD_TOKEN: ${{ secrets.toolkit_cli_download_token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Composite Action
        uses: ./.github/actions/common-setup
        shell: bash
        with:
          toolkit_cli_download_token: $TOOLKIT_CLI_DOWNLOAD_TOKEN
          toolkit_cli_version: $TOOLKIT_CLI_VERSION
          snowflake_private_key_pem: $SNOWFLAKE_PRIVATE_KEY_PEM

      - name: Create metadata
        shell: bash
        run: toolkit provision init --metadata

      - name: Plan on pull request
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          toolkit provision apply --plan

      - name: Apply changes on merge to master
        shell: bash
        run: |
          toolkit provision apply
        if: github.event_name == 'push'
